name: build in a big endian architecture

on: [push, pull_request, workflow_dispatch]

jobs:
  # inspired by https://github.com/alpacahq/easyjson/blob/master/.github/workflows/easyjson.yml
  test-non-amd64:
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: s390x
            distro: ubuntu_latest
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@master
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          install: |
            apt-get update
            apt install -y build-essential
          run: |
            make
